-- Módulo Fiscal Fase 1: Campos fiscais na Company, NfeImport e NfeImportItem

-- ============ Company — Regime tributário e contabilista ============

ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'SN';
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "crt" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "cnae" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "suframa" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "fiscalProfile" TEXT NOT NULL DEFAULT 'A';
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistName" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistCpf" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistCrc" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistCnpj" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistCep" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistPhone" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "contabilistEmail" TEXT;

-- ============ NfeImport — Totais tributários da nota ============

ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "indOper" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "finNfe" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "codSit" TEXT;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "baseIcmsCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "icmsCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "baseIcmsStCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "icmsStCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "ipiCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "pisCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "cofinsCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "freteCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "seguroCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "descontoCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "outrasDespCents" INTEGER;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "infCpl" TEXT;
ALTER TABLE "NfeImport" ADD COLUMN IF NOT EXISTS "xmlContent" TEXT;

-- ============ NfeImportItem — Campos tributários por item ============

ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "cstIcms" TEXT;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "modBcIcms" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "baseIcmsCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "aliqIcms" DOUBLE PRECISION;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "icmsCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "baseIcmsStCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "aliqIcmsSt" DOUBLE PRECISION;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "icmsStCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "cstIpi" TEXT;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "baseIpiCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "aliqIpi" DOUBLE PRECISION;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "ipiCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "cstPis" TEXT;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "basePisCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "aliqPis" DOUBLE PRECISION;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "pisCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "cstCofins" TEXT;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "baseCofinsCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "aliqCofins" DOUBLE PRECISION;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "cofinsCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "freteCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "seguroCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "descontoCents" INTEGER;
ALTER TABLE "NfeImportItem" ADD COLUMN IF NOT EXISTS "outrasDespCents" INTEGER;
